### ISSUE TITLE
Bug: Rock of ages->Defining the Models-> Video Walkthrough link is broken

### ISSUE THREAD

**Issue by Sydney-M-Sharp** [day-cohort-70/server-side-python-curriculum#1]
Bug: Rock of ages->Defining the Models-> Video Walkthrough link is broken

When try to access this [link](https://watch.screencastify.com/v/vyrXoRQVjaoBycysiIal) there is no video shown. 
![Screenshot 2024-06-13 at 2 28 11 PM](https://github.com/day-cohort-70/server-side-python-curriculum/assets/159806068/ffd0d703-e01b-4be9-804d-f2c5c73512c7)

**Comment by stevebrownlee** [comment]
This link works. Screencastify was, perhaps, having network issues at the time.
